//! Embeds every shipped company bundle's `agents/` directory into the binary.
//!
//! The roster moved out of `company.toml` and into `agents/*.toml`. The on-disk
//! path followed it, but a `DesktopPreset` carries only an `include_str!`'d
//! `company.toml`, and `include_str!` cannot glob a directory — so the embedded
//! path silently lost every teammate, and first-run seeded an empty company.
//!
//! Generating the table here rather than hand-listing 135 files in a macro is
//! the point: a teammate added to a bundle is embedded because it exists, not
//! because someone remembered to add a line. A forgotten entry would not fail
//! the build, it would ship a company missing one agent.
//!
//! Both `*.toml` rosters and the documents `prompt_files` names are embedded,
//! because `agent_file::resolve_prompt_files` reads those bodies at parse time.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

fn main() {
    let root = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let companies = root.join("companies");

    // Re-run when a bundle changes. Watching `companies/` alone is not enough:
    // cargo does not walk into it, so a new agent file inside an existing
    // bundle would not invalidate the build.
    println!("cargo:rerun-if-changed={}", companies.display());

    let mut bundles: BTreeMap<String, Vec<(String, String)>> = BTreeMap::new();

    let Ok(entries) = std::fs::read_dir(&companies) else {
        // No `companies/` at all is not this script's business to fail on:
        // the crate still compiles, and the desktop tests are what assert the
        // catalog is present.
        write_table(&bundles);
        return;
    };

    for entry in entries.filter_map(Result::ok) {
        let bundle = entry.path();
        if !bundle.is_dir() {
            continue;
        }
        let Some(id) = bundle.file_name().and_then(|n| n.to_str()) else {
            continue;
        };
        let agents_dir = bundle.join("agents");
        if !agents_dir.is_dir() {
            continue;
        }
        println!("cargo:rerun-if-changed={}", agents_dir.display());

        let mut files = Vec::new();
        collect(&agents_dir, &agents_dir, &mut files);
        // Sorted by path, matching `agent_file::agent_file_paths`, because the
        // roster's order decides which teammate orchestrates when nobody is
        // tagged.
        files.sort_by(|a, b| a.0.cmp(&b.0));
        if !files.is_empty() {
            bundles.insert(id.to_string(), files);
        }
    }

    write_table(&bundles);
}

/// Every file under `agents/`, keyed by its path relative to that directory.
///
/// Recursive because `prompt_files` entries live in subdirectories beside the
/// agent that names them; the consumer is what restricts *roster* parsing to
/// the immediate directory.
fn collect(base: &Path, dir: &Path, out: &mut Vec<(String, String)>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.filter_map(Result::ok) {
        let path = entry.path();
        if path.is_dir() {
            collect(base, &path, out);
            continue;
        }
        let Ok(rel) = path.strip_prefix(base) else {
            continue;
        };
        // Forward slashes regardless of host, so the embedded keys match the
        // `prompt_files` entries authors write.
        let key = rel
            .components()
            .filter_map(|c| c.as_os_str().to_str())
            .collect::<Vec<_>>()
            .join("/");
        match std::fs::read_to_string(&path) {
            Ok(body) => out.push((key, body)),
            // A non-UTF-8 file under `agents/` is not a roster file and not a
            // prompt document. Skipping it keeps a stray binary from failing
            // every build.
            Err(_) => continue,
        }
    }
}

fn write_table(bundles: &BTreeMap<String, Vec<(String, String)>>) {
    let mut out = String::from(
        "// @generated by build.rs — do not edit.\n\
         /// Every shipped bundle's `agents/` directory, keyed by company id.\n\
         /// Inner entries are paths relative to `agents/`, sorted.\n\
         pub static EMBEDDED_AGENT_BUNDLES: &[(&str, &[(&str, &str)])] = &[\n",
    );
    for (id, files) in bundles {
        out.push_str(&format!("    ({id:?}, &[\n"));
        for (name, body) in files {
            out.push_str(&format!("        ({name:?}, {body:?}),\n"));
        }
        out.push_str("    ]),\n");
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("embedded_agents.rs");
    std::fs::write(dest, out).unwrap();
}
