#!/usr/bin/env python3
"""Drive the Hive Math Lab through a ladder of Project Euler problems, headlessly.

For each problem: state it in the ``solvers`` desk, pump the approvals queue
(``shell`` parks on every policy tier, so an unattended run has to answer it),
wait for the hive episode to end (a ``hive-report`` bubble on the desk), and
compare the integer the room converged on against the published answer.

Stdlib only, so it runs wherever ``python3`` does. Talks to a running
``opencompany serve`` (default ``http://127.0.0.1:8080``) whose auth mode is
``none``, or signs in as the manifest admin through the dev-code flow when the
host echoes one (loopback, no public URL).

    python3 scripts/hive-euler.py --problems 1,5,12,31,60,100
    python3 scripts/hive-euler.py --base http://127.0.0.1:8080 --desk solvers --timeout 1500

Exit status is the number of problems the room got wrong or failed to finish,
so a CI-style caller can treat zero as green. A JSON transcript of every run is
written next to the summary (``--out``) for reading afterwards.
"""

from __future__ import annotations

import argparse
import http.cookiejar
import json
import re
import sys
import time
import urllib.error
import urllib.parse
import urllib.request

SCOPE = "/api/v1/company"
ADMIN_EMAIL = "harness-e2e@tinyhumans.ai"
HIVE_REPORT_AUTHOR = "hive-report"

# The ladder. Statements are given in full because the lab holds no `web`
# grant; answers are the published ones (projecteuler-solutions).
PROBLEMS: dict[str, dict[str, str]] = {
    "1": {
        "title": "Multiples of 3 or 5",
        "answer": "233168",
        "statement": (
            "If we list all the natural numbers below 10 that are multiples of 3 or 5, we get "
            "3, 5, 6 and 9. The sum of these multiples is 23.\n\n"
            "Find the sum of all the multiples of 3 or 5 below 1000."
        ),
    },
    "5": {
        "title": "Smallest multiple",
        "answer": "232792560",
        "statement": (
            "2520 is the smallest number that can be divided by each of the numbers from 1 to "
            "10 without any remainder.\n\n"
            "What is the smallest positive number that is evenly divisible by all of the "
            "numbers from 1 to 20?"
        ),
    },
    "12": {
        "title": "Highly divisible triangular number",
        "answer": "76576500",
        "statement": (
            "The sequence of triangle numbers is generated by adding the natural numbers. So "
            "the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten "
            "terms would be: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...\n\n"
            "Let us list the factors of the first seven triangle numbers:\n"
            "  1: 1\n  3: 1,3\n  6: 1,2,3,6\n  10: 1,2,5,10\n  15: 1,3,5,15\n"
            "  21: 1,3,7,21\n  28: 1,2,4,7,14,28\n\n"
            "We can see that 28 is the first triangle number to have over five divisors.\n\n"
            "What is the value of the first triangle number to have over five hundred divisors?"
        ),
    },
    "14": {
        "title": "Longest Collatz sequence",
        "answer": "837799",
        "statement": (
            "The following iterative sequence is defined for the set of positive integers: "
            "n -> n/2 (n is even), n -> 3n + 1 (n is odd).\n\n"
            "Using the rule above and starting with 13, we generate the following sequence: "
            "13 -> 40 -> 20 -> 10 -> 5 -> 16 -> 8 -> 4 -> 2 -> 1. It can be seen that this "
            "sequence (starting at 13 and finishing at 1) contains 10 terms. Although it has "
            "not been proved yet (Collatz Problem), it is thought that all starting numbers "
            "finish at 1.\n\n"
            "Which starting number, under one million, produces the longest chain?\n\n"
            "NOTE: Once the chain starts the terms are allowed to go above one million."
        ),
    },
    "31": {
        "title": "Coin sums",
        "answer": "73682",
        "statement": (
            "In the United Kingdom the currency is made up of pound (£) and pence (p). There "
            "are eight coins in general circulation: 1p, 2p, 5p, 10p, 20p, 50p, £1 (100p), and "
            "£2 (200p).\n\n"
            "It is possible to make £2 in the following way: 1×£1 + 1×50p + 2×20p + 1×5p + "
            "1×2p + 3×1p.\n\n"
            "How many different ways can £2 be made using any number of coins?"
        ),
    },
    "60": {
        "title": "Prime pair sets",
        "answer": "26033",
        "statement": (
            "The primes 3, 7, 109, and 673, are quite remarkable. By taking any two primes "
            "and concatenating them in any order the result will always be prime. For "
            "example, taking 7 and 109, both 7109 and 1097 are prime. The sum of these four "
            "primes, 792, represents the lowest sum for a set of four primes with this "
            "property.\n\n"
            "Find the lowest sum for a set of five primes for which any two primes "
            "concatenate to produce another prime."
        ),
    },
    "92": {
        "title": "Square digit chains",
        "answer": "8581146",
        "statement": (
            "A number chain is created by continuously adding the square of the digits in a "
            "number to form a new number until it has been seen before.\n\n"
            "For example, 44 -> 32 -> 13 -> 10 -> 1 -> 1 and 85 -> 89 -> 145 -> 42 -> 20 -> "
            "4 -> 16 -> 37 -> 58 -> 89. Therefore any chain that arrives at 1 or 89 will "
            "become stuck in an endless loop. What is most amazing is that EVERY starting "
            "number will eventually arrive at 1 or 89.\n\n"
            "How many starting numbers below ten million will arrive at 89?"
        ),
    },
    "100": {
        "title": "Arranged probability",
        "answer": "756872327473",
        "statement": (
            "If a box contains twenty-one coloured discs, composed of fifteen blue discs and "
            "six red discs, and two discs were taken at random, it can be seen that the "
            "probability of taking two blue discs, P(BB) = (15/21) x (14/20) = 1/2.\n\n"
            "The next such arrangement, for which there is exactly a 50% chance of taking two "
            "blue discs at random, is a box containing eighty-five blue discs and thirty-five "
            "red discs.\n\n"
            "By finding the first arrangement to contain over 10^12 = 1,000,000,000,000 discs "
            "in total, determine the number of blue discs that the box would contain."
        ),
    },
    "145": {
        "title": "How many reversible numbers are there below one-billion?",
        "answer": "608720",
        "statement": (
            "Some positive integers n have the property that the sum [ n + reverse(n) ] "
            "consists entirely of odd (decimal) digits. For instance, 36 + 63 = 99 and "
            "409 + 904 = 1313. We will call such numbers reversible; so 36, 63, 409, and 904 "
            "are reversible. Leading zeroes are not allowed in either n or reverse(n).\n\n"
            "There are 120 reversible numbers below one-thousand.\n\n"
            "How many reversible numbers are there below one-billion (10^9)?"
        ),
    },
}


class Host:
    """A cookie-carrying HTTP client for one OpenCompany host."""

    def __init__(self, base: str) -> None:
        self.base = base.rstrip("/")
        self.jar = http.cookiejar.CookieJar()
        self.opener = urllib.request.build_opener(urllib.request.HTTPCookieProcessor(self.jar))

    def call(self, method: str, path: str, body: dict | None = None, timeout: float = 120):
        data = None if body is None else json.dumps(body).encode()
        req = urllib.request.Request(self.base + path, data=data, method=method)
        req.add_header("accept", "application/json")
        if data is not None:
            req.add_header("content-type", "application/json")
        try:
            with self.opener.open(req, timeout=timeout) as resp:
                raw = resp.read()
                return resp.status, (json.loads(raw) if raw else None)
        except urllib.error.HTTPError as err:
            raw = err.read()
            try:
                return err.code, json.loads(raw)
            except ValueError:
                return err.code, raw.decode(errors="replace")

    def sign_in(self) -> None:
        """No-op when auth is `none`; otherwise the loopback dev-code flow."""
        status, _ = self.call("GET", f"{SCOPE}/chat/history?limit=1")
        if status == 200:
            return
        status, body = self.call("POST", f"{SCOPE}/auth/request", {"email": ADMIN_EMAIL})
        code = (body or {}).get("dev_code") if isinstance(body, dict) else None
        if not code:
            raise SystemExit(f"sign-in: no dev_code from auth/request ({status}: {body})")
        status, body = self.call("POST", f"{SCOPE}/auth/verify", {"code": code})
        if status >= 300:
            raise SystemExit(f"sign-in: verify refused ({status}: {body})")

    # -- the operator's two jobs: stating the problem and answering approvals --

    def say(self, desk: str, text: str) -> None:
        status, body = self.call("POST", f"{SCOPE}/chat", {"text": text, "chat": desk}, timeout=3600)
        if status >= 300:
            raise RuntimeError(f"chat POST failed ({status}): {body}")

    def approve_all(self) -> list[str]:
        status, body = self.call("GET", f"{SCOPE}/approvals")
        if status != 200 or not isinstance(body, list):
            return []
        approved = []
        for approval in body:
            aid = approval.get("id")
            status, _ = self.call(
                "POST", f"{SCOPE}/approvals/{aid}", {"verdict": "approve", "detach": True}
            )
            if status < 300:
                approved.append(approval.get("kind", "?"))
        return approved

    def history(self, desk: str, limit: int = 200) -> list[dict]:
        query = urllib.parse.urlencode({"desk": desk, "limit": limit})
        status, body = self.call("GET", f"{SCOPE}/chat/history?{query}")
        if status != 200 or not isinstance(body, list):
            return []
        return body


INT = re.compile(r"\d{1,3}(?:,\d{3})+|\d+")


def integers_in(text: str) -> list[str]:
    return [t.replace(",", "") for t in INT.findall(text)]


def wait_for_report(host: Host, desk: str, after_id: int, timeout: float, log) -> tuple[dict | None, list[dict]]:
    """Poll the desk until a hive-report bubble newer than `after_id` lands."""
    deadline = time.time() + timeout
    seen: set[str] = set()
    approved_total: list[str] = []
    while time.time() < deadline:
        approved = host.approve_all()
        if approved:
            approved_total.extend(approved)
            log(f"    approved: {', '.join(approved)}")
        messages = [m for m in host.history(desk) if int(m.get("id", "0")) > after_id]
        for m in messages:
            if m["id"] not in seen:
                seen.add(m["id"])
                first = m.get("text", "").strip().splitlines()[:1]
                log(f"    [{m['id']}] {m.get('author')}: {first[0] if first else ''}")
        report = next((m for m in messages if m.get("author") == HIVE_REPORT_AUTHOR), None)
        if report:
            return report, messages
        time.sleep(5)
    return None, [m for m in host.history(desk) if int(m.get("id", "0")) > after_id]


def run_problem(host: Host, desk: str, pid: str, timeout: float, log) -> dict:
    problem = PROBLEMS[pid]
    before = host.history(desk, limit=1)
    after_id = int(before[-1]["id"]) if before else 0
    text = (
        f"Project Euler {pid}: {problem['title']}.\n\n{problem['statement']}\n\n"
        "Decide the answer as a desk: propose a candidate only once a program has printed it, "
        "support only a number you independently checked, and object to anything that did not "
        "come out of a run."
    )
    log(f"== Problem {pid} ({problem['title']}) — expecting {problem['answer']}")
    started = time.time()
    host.say(desk, text)
    report, messages = wait_for_report(host, desk, after_id, timeout, log)
    elapsed = round(time.time() - started, 1)
    turns = [m for m in messages if m.get("author") not in (HIVE_REPORT_AUTHOR,) and not m.get("mine")]
    outcome = {
        "problem": pid,
        "title": problem["title"],
        "expected": problem["answer"],
        "elapsed_s": elapsed,
        "turns": len(turns),
        "report": report.get("text") if report else None,
        "messages": messages,
    }
    if report is None:
        outcome["verdict"] = "timeout"
    else:
        rtext = report.get("text", "")
        converged = "Converged" in rtext or "converged" in rtext
        found = integers_in(rtext)
        # The report names the carried topic; a topic is usually the number
        # itself (`#233168`) but a room may name it otherwise, so fall back to
        # the last supporting line's integers.
        if problem["answer"] not in found:
            for m in reversed(turns):
                if problem["answer"] in integers_in(m.get("text", "")):
                    found.append(problem["answer"])
                    break
        outcome["converged"] = converged
        outcome["verdict"] = (
            "correct" if converged and problem["answer"] in found else
            "wrong" if converged else
            "undecided"
        )
    log(f"   -> {outcome['verdict']} after {len(turns)} turns in {elapsed}s")
    return outcome


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--base", default="http://127.0.0.1:8080")
    ap.add_argument("--desk", default="solvers")
    ap.add_argument("--problems", default="1,5,12,31,60,100")
    ap.add_argument("--timeout", type=float, default=1500, help="seconds per problem")
    ap.add_argument("--out", default="hive-euler-results.json")
    args = ap.parse_args()

    def log(line: str) -> None:
        print(line, flush=True)

    host = Host(args.base)
    host.sign_in()
    results = []
    for pid in [p.strip() for p in args.problems.split(",") if p.strip()]:
        if pid not in PROBLEMS:
            log(f"!! unknown problem {pid}; known: {', '.join(PROBLEMS)}")
            continue
        results.append(run_problem(host, args.desk, pid, args.timeout, log))
        with open(args.out, "w") as fh:
            json.dump(results, fh, indent=2)

    log("")
    log("problem | verdict   | turns | seconds")
    log("--------|-----------|-------|--------")
    for r in results:
        log(f"{r['problem']:>7} | {r['verdict']:<9} | {r['turns']:>5} | {r['elapsed_s']}")
    return sum(1 for r in results if r["verdict"] != "correct")


if __name__ == "__main__":
    sys.exit(main())
